name: wave_clone
description: Wave mobile money clone application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  dio: ^5.3.2
  flutter_svg: ^2.0.14
  google_fonts: ^6.1.0
  qr_flutter: ^4.1.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/papa.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo/papa.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo/next.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/logo/next.png
  android_12:
    image: assets/images/logo/papa.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/logo/next.png
    icon_background_color_dark: "#FFFFFF"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo/pis.jpeg
    - assets/images/logo/next.png
    - assets/images/logo/nexus.png
    - assets/images/logo/papa.png


